### ISSUE TITLE
Use of <<

### ISSUE THREAD

**Issue by devrandom** [rtkwlf/cookbook-simple-iptables#37]
Undefined node attribute or method '<<' on 'node'. To set an attribute, use `<<=value' instead.
## Cookbook Trace:

/root/chef/cookbooks/simple-iptables/providers/rule.rb:16:in `block in class_from_file'

**Comment by JessicaHeres** [comment]
@Kasen thanks that fixed my error :)

**Comment by joost** [comment]
@Kasen thx :)
