### ISSUE TITLE
Please upload new version

### ISSUE THREAD

**Issue by dblessing** [rtkwlf/cookbook-simple-iptables#62]
There are lots of nice improvements since the last upload to the SuperMarket. Namely, the comment feature is what I'm looking for. Can you please upload a new version?

**Comment by rtkrruvinskiy** [comment]
@dblessing Sorry about the delay! I've cut a 0.7.1 release and published it on Supermarket: https://supermarket.chef.io/cookbooks/simple_iptables

**Comment by dblessing** [comment]
Thanks @rtkrruvinskiy. It wasn't too long a wait.
