### ISSUE TITLE
kitchen converge gives error when using chef 12.5.1

### ISSUE THREAD

**Issue by akhan002** [rtkwlf/cookbook-simple-iptables#77]
Hi,

I get the following error when going a kitchen converge using chef 12.5.1:

       ================================================================================
       Recipe Compile Error in /tmp/kitchen/cache/cookbooks/simple_iptables/resources/policy.rb
       ================================================================================

       NameError
       ---------
       undefined method `log_deprecation' for class `Class'

       Cookbook Trace:
       ---------------
         /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef.rb:6:in `method'
         /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef.rb:6:in `log_deprecation'
         /tmp/kitchen/cache/cookbooks/simple_iptables/resources/policy.rb:3:in `class_from_file'
         /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/resource/lwrp_base.rb:50:in `build_from_file'

       Relevant File Content:
       ----------------------
       /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef.rb:

         1:  class Chef
         2:    NOT_PASSED = Object.new if !defined?(NOT_PASSED)
         3:    # Earlier versions of Chef didn't have this message
         4:    module ChefCompatDeprecation
         5:      def log_deprecation(message, location=nil)
         6>>       if superclass.method(:log_deprecation).owner != ChefCompatDeprecation
         7:          if !location
         8:            # Pick the first caller that is *not* part of the Chef or ChefCompat gem,
         9:            # that's the thing the user wrote.
        10:            chef_compat_gem_path = File.expand_path("../../..", __FILE__)
        11:            chef_gem_path = File.expand_path("../..",::Chef::Resource.instance_method(:initialize).source_location[0])
        12:            caller(0..10).each do |c|
        13:              if !c.start_with?(chef_gem_path) && !c.start_with?(chef_compat_gem_path)
        14:                location = c
        15:                break

       Running handlers:
       [2015-11-02T10:53:24+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2015-11-02T10:53:24+00:00] ERROR: Exception handlers complete
       Chef Client failed. 0 resources updated in 12 seconds
       [2015-11-02T10:53:24+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2015-11-02T10:53:24+00:00] ERROR: undefined method `log_deprecation' for class `Class'
       [2015-11-02T10:53:26+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
>>>>>> Converge failed on instance <default-centos-66>.
>>>>>> Please see .kitchen/logs/default-centos-66.log for more details
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: SSH exited (1) for command: [sh -c '

sudo -E /opt/chef/bin/chef-client --local-mode --config /tmp/kitchen/client.rb --log_level auto --force-formatter --no-color --json-attributes /tmp/kitchen/dna.json --chef-zero-port 8889
']

**Comment by Kasen** [comment]
I can offer a workaround: you need to constraint version of compat_resource cookbook to 12.5.10.

**Comment by rtkrruvinskiy** [comment]
@akhan002 This appears to be an issue with the compat_resource cookbook, and it is being tracked in https://github.com/chef-cookbooks/compat_resource/issues/7. Until it's resolved, please follow @Kasen's workaround suggestion.
